---
title: "P8105_hw5_jl5172"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
```

```{r,echo=FALSE,message=F}
all_files<-list.files("./data/",full.names = T)

df<- all_files %>% 
  map(read_csv)

for(i in 1:length(all_files)){
  if(i<=10){
   df[[i]]<-df[[i]] %>% 
     mutate(control_arm="Control",id=i)
  } else if (i>=11){
     df[[i]]<-df[[i]] %>% 
       mutate(control_arm="Experiment",id=i)
   }
}


```


```{r}
df<-bind_rows(df)
df<-df %>% 
  janitor::clean_names() %>% 
  as.tibble()
df
```

```{r,fig.width =12}
df %>% 
  gather(key=week,value=data,week_1:week_8) %>% 
  ggplot(aes(x=week,y=data,color=control_arm, group =id))+
  geom_line()+geom_point(size=0.1)+
  facet_grid(~control_arm)+
  labs(title="Plot for Observations Over Weeks ",xlab="Week",ylab="Observation")

```


#Question 2
```{r}
homicide<-read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")
```


```{r}
homicide_summary<- homicide %>% 
  mutate(city_state=str_c(city,state,sep=",")) %>% 
  group_by(city_state) %>% 
  summarise(homicide_cases=n())
  
```


```{r}
unsolved_summary<-homicide %>% 
  mutate(city_state=str_c(city,state,sep=",")) %>% 
  filter(disposition=="Closed without arrest"|disposition=="Open/No arrest") %>%   group_by(city_state) %>% 
  summarise(unsolved=n())
  
```


```{r}
combined_summary = 
  left_join(homicide_summary,unsolved_summary,by="city_state") 
```


```{r}
Homicide_Baltimore<-combined_summary %>% 
  filter(city_state=="Baltimore,MD") 

Baltimore_prop_t<-prop.test(Homicide_Baltimore$unsolved,Homicide_Baltimore$homicide_cases)

broom::tidy(Baltimore_prop_t) %>% 
select(estimate, conf.low, conf.high)

```



